# Generated by Django 3.2.6 on 2021-08-24 11:36

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название тега')),
                ('slug', models.SlugField(help_text='Ссылка тега', unique=True, verbose_name='Ссылка')),
                ('color', colorfield.fields.ColorField(choices=[('#FFFFFF', 'white'), ('#000000', 'black'), ('#00FF00', 'green'), ('#FF00FF', 'pink panther'), ('#FF9900', 'orange'), ('#CC0000', 'cherry'), ('#CC00FF', 'purple')], default='#FFFFFF', max_length=18, verbose_name='Цвет тэга')),
            ],
            options={
                'verbose_name': 'Тэг',
            },
        ),
    ]
