# Generated by Django 3.2.6 on 2021-08-09 06:54

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18, verbose_name='Цвет тэга'),
        ),
    ]
