# Generated by Django 3.2.6 on 2021-08-09 07:01

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_alter_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(choices=[('#FFFFFF', 'white'), ('#000000', 'black'), ('#00FF00', 'green'), ('#FF00FF', 'pink panther'), ('#FF9900', 'orange'), ('#CC0000', 'cherry'), ('#CC00FF', 'purple')], default='#FFFFFF', max_length=18, verbose_name='Цвет тэга'),
        ),
    ]
