# Generated by Django 3.2.6 on 2021-08-08 08:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации')),
                ('text', models.TextField(max_length=1000, verbose_name='Описание')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
                ('cooking_time', models.CharField(max_length=200, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время готовки в минутах')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор рецепта')),
                ('ingredients', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='ingredients.ingredient', verbose_name='Ингредиенты')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
