# Generated by Django 3.2.6 on 2021-08-11 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='recipe',
            new_name='favorite',
        ),
    ]
