# Generated by Django 3.2.6 on 2021-08-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_alter_tag_color'),
        ('recipes', '0007_ingredientamount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tag',
        ),
        migrations.AddField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(default='', null=True, to='tags.Tag', verbose_name='Хэштег'),
        ),
    ]
