# Generated by Django 3.2.6 on 2021-08-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_alter_tag_color'),
        ('recipes', '0009_alter_ingredientamount_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(default='', to='tags.Tag', verbose_name='Хэштег'),
        ),
    ]
